### ISSUE TITLE
ESP32 Support

### ISSUE THREAD

**Issue by maddisondesigns** [earlephilhower/arduino-littlefs-upload#10]
Hi,

Just wondering if you're looking to get this working with ESP32 boards? Currently when I try to upload I get the following error:

```ERROR: Only Arduino-Pico RP2040 and ESP8266 supported.```

I updated to the latest nightly build before the above test.
```
Version: 2.2.2-nightly-20240101
Date: 2024-01-01T03:13:38.842Z
```

**Comment by earlephilhower** [comment]
Sorry, the whole filesystem infrastructure is very different for the ESP32 vs. the other two.  So while the filesystem binary will be the same there's a lot of wrapper around it different (i.e. partitions, etc.).  I'm also very unfamiliar with the ESP32 Arduino setup so even if I somehow did add it, it probably wouldn't be what most people would expect. :laughing: 

I think @dankeboy36 was working on an ESP32 version, you might check his repos.  I believe he was the one who actually added the APIs to get the Arduino variables into the plugins, and was very helpful in getting my own extension working.
