### ISSUE TITLE
How do change the length of the littlefs.bin file ?

### ISSUE THREAD

**Issue by hajogegit** [earlephilhower/arduino-littlefs-upload#11]
A fatal esptool.py error occurred: File C:\Users\User\AppData\Local\Temp\tmp-19560-x1JsfZZnJqGM-.littlefs.bin (length 7315456) at offset 1048576 will not fit in 1048576 bytes of flash. Use --flash-size argument, or change flashing address.

How do change the length of the littlefs.bin file ?

**Comment by earlephilhower** [comment]
Select the proper file system size in the IDE menu.
