### ISSUE TITLE
ERROR: No data folder found

### ISSUE THREAD

**Issue by cvjmilos** [earlephilhower/arduino-littlefs-upload#13]
I have 'data' folder within sketch folder, and the file I want to upload is in 'data' folder, but after I choose [Ctrl] + [Shift] + [P], then "Upload LittleFS to Pico/ESP8266", all I get is:

LittleFS Filesystem Uploader

ERROR: No data folder found

I am uploading to ESP8266, port is okay.

**Comment by fabioroldan** [comment]
I have the same problem

**Comment by hasaranga** [comment]
same for rp2040

**Comment by markingle** [comment]
I have the same problem

**Comment by lukbieli** [comment]
I had the same problem. It helped to close and reopen Arduino / Project window.
