### ISSUE TITLE
No "Upload LittleFS to Pico/ESP8266" found in Arduino IDE 2.2.1 after installed

### ISSUE THREAD

**Issue by Metaphorme** [earlephilhower/arduino-littlefs-upload#2]
Hi Philhower!
&ensp;So grateful for your work! But I meet some problems during using this plugin.
&ensp;I downloaded [arduino-littlefs-upload-1.0.0.vsix](https://github.com/earlephilhower/arduino-littlefs-upload/releases/download/1.0.0/arduino-littlefs-upload-1.0.0.vsix) from release page and place it into `~/.arduinoIDE/plugins/`, but nothing changed in my tool menu. After that, I tried to put it in both `~/.arduinoIDE/plugins/` and `~/.arduinoIDE/plugin-storage`, and nothing changed. Then, I downloaded [arduino-littlefs-upload-1.0.0.vsix](https://github.com/earlephilhower/arduino-littlefs-upload/blob/1.0.0/arduino-littlefs-upload-1.0.0.vsix) from git branch and place it into both `~/.arduinoIDE/plugins/` and `~/.arduinoIDE/plugin-storage`, and nothing changed. By the way, [Ctrl] + [Shift] + [P] don't work on my mac, as a result I try to find in tool menu.
&ensp;I'm sorry that I'm new to arduino and something I do maybe roughly, but I'm so appreciat if you could help me to fix this problem.

### Environment:

- macOS 14.0
- Arduino IDE 2.2.1
- ESP 8266

### Pictures:
<img width="535" alt="截屏2023-10-24 23 51 57" src="https://github.com/earlephilhower/arduino-littlefs-upload/assets/102651183/300a0283-e4fd-46b8-adcd-1d3a5b2cef1e">

My tool menu.
 
<img width="771" alt="截屏2023-10-24 23 48 25" src="https://github.com/earlephilhower/arduino-littlefs-upload/assets/102651183/7c3851f6-c2bf-4501-b85e-d17e51f56258">

Place I put arduino-littlefs-upload-1.0.0.vsix in.

**Comment by dankeboy36** [comment]
> but nothing changed in my tool menu

This is expected, @Metaphorme. It's a lack of feature in the Arduino IDE: https://github.com/arduino/arduino-ide/issues/2135. You won't see menu items contributed by extensions. Here is a related discussion: https://github.com/dankeboy36/vscode-arduino-api/discussions/8.

> By the way, [Ctrl] + [Shift] + [P]

On macOS, you have to press <kbd>⌘</kbd>+<kbd>Shift</kbd>+<kbd>P</kbd> to open the _Commad  Palette_ in the Arduino IDE. Then, you should see the `Upload LittleFS to Pico/ESP8266` command.

**Comment by earlephilhower** [comment]
Thanks, @dankeboy36 .  When I get back home in a couple weeks I'll update the `readme.md` with the Mac key sequence you listed!

**Comment by Metaphorme** [comment]
I found it! Thank you! ☺️
