### ISSUE TITLE
esptool not found

### ISSUE THREAD

**Issue by aziemer** [earlephilhower/arduino-littlefs-upload#23]
First of all: thank you for your plugin, as it is the only (easy) way to upload to the SPIFFS area on the ESP.

But... your plugin tries to call the Python version of the ESP Tool (esptool.py) - which is not installed, there is only the compiled version in the tools folder. 

I'm on a Mac mini with M2 processor and Arduino IDE 2.3.2.

If your plugin would i.e. call

`/Users/aziemer/Library/Arduino15/packages/esp32/tools/esptool_py/4.5.1/esptool`

instead of

`python3 /Users/aziemer/Library/Arduino15/packages/esp32/tools/esptool_py/4.5.1/esptool.py`

it should work. I don't know, if this is specific to the Mac with arm64 architecture or not.

best regards Andreas

**Comment by earlephilhower** [comment]
Can you give the VSIX in #24 a try and report back?  I don't have a Mac so can't do any testing there, but I think this will make it call the right command now.

**Comment by aziemer** [comment]
Your fix works perfect! THANK YOU VERY MUCH - especially for the your reply !

best regards
Andreas
