### ISSUE TITLE
Partition entry not found in csv file!

### ISSUE THREAD

**Issue by TruDataRx-Mark** [earlephilhower/arduino-littlefs-upload#29]
No matter which partition scheme I choose, I get the same error.

LittleFS Filesystem Uploader

Using partition: tinyuf2-partitions-4MB
ERROR: Partition entry not found in csv file!

I am running on a Mac Book Pro with an M1.  I am trying to push files onto an ESP32-S3 from Adafruit.  I can deploy and run code from the Arduino IDE, but I am unable to get resource files onto the SPIFFS file system.

**Comment by earlephilhower** [comment]
That file has no `spiffs` (which is now used for LittleFS) partition defined, so the uploader can't make one.  It looks like it's a FAT-only filesystem defined which this does not support

````
$ cat tools/partitions/tinyuf2-partitions-4MB.csv

# ESP-IDF Partition Table
# Name,   Type, SubType, Offset,  Size, Flags
# bootloader.bin,,          0x1000, 32K
# partition table,          0x8000, 4K

nvs,      data, nvs,      0x9000,  20K,
otadata,  data, ota,      0xe000,  8K,
ota_0,    app,  ota_0,   0x10000,  1408K,
ota_1,    app,  ota_1,  0x170000,  1408K,
uf2,      app,  factory,0x2d0000,  256K,
ffat,     data, fat,    0x310000,  960K,
````
