### ISSUE TITLE
Folders

### ISSUE THREAD

**Issue by AllenM001** [earlephilhower/arduino-littlefs-upload#30]
This appears to copy only files on the root level. Is there any possibility that folder contents will be added? Thanks.

**Comment by earlephilhower** [comment]
This just calls `mklittlefs` which handles the filesystem filling.  But in any case mklittlefs does include subdirectories automatically (note the file list shown in a quick test below):
````
...
Building LittleFS filesystem
/home/earle/Arduino/hardware/pico/rp2040/system/mklittlefs/mklittlefs -c /home/earle/Arduino/_/data -p 256 -b 4096 -s 65536 /tmp/tmp-1271534-UGfOKnAwVpI5-.littlefs.bin

/sub1/test
/_.ino
...
````
