### ISSUE TITLE
No data folder found

### ISSUE THREAD

**Issue by markingle** [earlephilhower/arduino-littlefs-upload#31]
I am using an ESP32 Dev Module running Arduino 2.3.2.  I have the following data directory with my sketch

C:\Users\marka\Documents\Arduino\Aerator_Livewell_Switch\data

**Comment by earlephilhower** [comment]
This is an IDE glitch, nothing to do here.  See the [workaround for the serial port,](https://github.com/earlephilhower/arduino-littlefs-upload?tab=readme-ov-file#glitches) the same should work here.

**Comment by markingle** [comment]
Hello!  The fix suggested does not work for me.  The plugin still indicates a missing data folder

**Comment by markingle** [comment]
![image](https://github.com/earlephilhower/arduino-littlefs-upload/assets/11239466/7d8ca052-3add-4c40-89ad-8a32d501def3)

![image](https://github.com/earlephilhower/arduino-littlefs-upload/assets/11239466/5a24bd1d-7b22-482b-8244-552ae5cedb0a)

**Comment by earlephilhower** [comment]
Try building the sketch once before doing the upload.  Either the IDE isn't reporting the proper value for the sketch directory, or it doesn't have permission to access files inside it (i.e. I've heard that OneDrive folders are sometimes weird that way).

**Comment by earlephilhower** [comment]
You can also try the more verbose version I just threw together which *may* shed some light on your particular problem.  Remove the 1.1.5 and download and install the 1.1.6 version and restart things and re-run.

https://github.com/earlephilhower/arduino-littlefs-upload/raw/talkie/arduino-littlefs-upload-1.1.6.vsix

**Comment by markingle** [comment]
Thank you!  I will give it a try now

**Comment by markingle** [comment]
Thank you for taking the time to provide some logging out put!  I had embedded the sketch directory within itself some how.....It could only be seen in the logging.

![image](https://github.com/earlephilhower/arduino-littlefs-upload/assets/11239466/caf7def8-91fb-4331-b743-e5e9feb2274f)

**Comment by markingle** [comment]
I recommend keeping the log output...
![image](https://github.com/earlephilhower/arduino-littlefs-upload/assets/11239466/36e1dd2f-41d9-4797-94fd-708947b8ff0e)

**Comment by earlephilhower** [comment]
Great, thanks for the follow up!  I've made that new version the release one and it'll hopefully make everyone's life easier.
