### ISSUE TITLE
Detect user-selected partitions file (and partitions.csv in sketch folder)

### ISSUE THREAD

**Issue by schmidtsamuelw** [earlephilhower/arduino-littlefs-upload#33]
First off, thank you for this plugin. I was expecting to have to write a shell script myself and awkwardly integrate it into my workflow until I stumbled upon this.

Currently, the plugin can only detect the partitions file set as the default for the selected board, ignoring the user's setting in the IDE and the sketch's partitions.csv file, if present. This causes issues in projects where the board's default partition scheme isn't being used, since the plugin will most likely be uploading to the incorrect location or allowing an upload when the actual partition scheme doesn't have a SPIFFS partition. The plugin should detect and use the same partitions file that will be used by the toolchain.

**Comment by earlephilhower** [comment]
Closed by #34
