### ISSUE TITLE
Suggestion: list of plugins compatible with Arduino IDE 2.0

### ISSUE THREAD

**Issue by MicSG-dev** [earlephilhower/arduino-littlefs-upload#36]
As a suggestion, there could be a list in some repository with plugins compatible with the Arduino IDE 2.0.
The ones I know are:
- [arduino-littlefs-upload](https://github.com/earlephilhower/arduino-littlefs-upload): LittleFS loader;
- [WakaTime for Arduino IDE](https://wakatime.com/arduino-ide): Fully automatic time control to assist with time management in each project.

**Comment by earlephilhower** [comment]
Why not start a forum post at [Arduino](https://forum.arduino.cc/) or make a repo yourself, like they do for the [Arduino Libraries](https://github.com/arduino/library-registry)?

**Comment by MicSG-dev** [comment]
Forum post created: https://forum.arduino.cc/t/list-of-plugins-compatible-with-arduino-ide-2-0
@earlephilhower Thanks for the suggestion.
