### ISSUE TITLE
Activating extension 'arduino-littlefs-upload' failed

### ISSUE THREAD

**Issue by mohdrais** [earlephilhower/arduino-littlefs-upload#37]
Hello, I got "Activating extension 'arduino-littlefs-upload' failed" when try to "Upload LittleFS to Pico/ESP8266/ESP32" due to: Cannot find ..\arduino-littlefs-upload\out\extension.js'. Required ...\backend\plugin-host.js. There is no \out\extensions.js in the VSIX file but there is backend\plugin-host.js.
By the way I am using Arduino IDE 2.3.2, Arduino-Pico V3.9.1 and window 11.

**Comment by mohdrais** [comment]
THank you. It worked.

**Comment by earlephilhower** [comment]
Thanks for the update!
