### ISSUE TITLE
Installation do not work actually on Arduino IDE2.3.2

### ISSUE THREAD

**Issue by hasenradball** [earlephilhower/arduino-littlefs-upload#47]
Hi,

tired to install on Arduino IDE 2.3.2.
But do not work actually.

![grafik](https://github.com/user-attachments/assets/53ef3877-95f9-4107-a433-3ed51bd798fa)

**Comment by buccaneer-jak** [comment]
Well not a lot of info in your post but it works fine for me using IDE 2.3.2 on 2 computers and for ESP32-WROOM, ESP32-S3 and ESP32-C6 so keep trying.
I suggest you read the Closed Issues to help you.

**Comment by hasenradball** [comment]
What more infor is needed?
Log files?

**Comment by hasenradball** [comment]
![grafik](https://github.com/user-attachments/assets/b8993edb-5d06-4a70-bd7c-663a51a53704)

work with strg + shift + P
