### ISSUE TITLE
ERROR: mklittlefs not found!

### ISSUE THREAD

**Issue by lbuque** [earlephilhower/arduino-littlefs-upload#49]
![image](https://github.com/user-attachments/assets/71baf79d-de99-42b0-84d7-c18f24029438)

**Comment by earlephilhower** [comment]
Posting a screenshot of text output, with no actual info on your setup (version, chip, etc.) is not very useful, but in this case it's pretty clear that the plug in is not finding mklittlefs in the appropriate place.  Make sure you've got a proper installation of the ESP32 toolchain and that mklittlefs exists in the `runtime.tools.mklittlefs.path` dir and that your user has permissions to run it.
