### ISSUE TITLE
Arduino IDE 2.1.1 for legacy support

### ISSUE THREAD

**Issue by aIecxs** [earlephilhower/arduino-littlefs-upload#54]
Arduino IDE 2.3.x cannot installed on Windows 7 Professional SP1 x64 (Build 7601) because of DiscardVirtualMemory Entry Point Missing From Kernel32.dll

Arduino IDE 2.1.1 ist the last version compatible with Windows 7. I have placed the vsix file under `%UserProfile%\.arduinoIDE\plugins\arduino-littlefs-upload-1.2.0.vsix`

when executed from Arduino IDE 2.1.1 `Upload LittleFS to Pico/ESP8266/ESP32` nothing happens. is there a way to make this work on Windows 7 / Arduino IDE 2.1.1 for legacy reasons?

**Comment by earlephilhower** [comment]
The IDE didn't add many of the needed hooks (or actually have them work repeatably!) until later versions, so if 2.1.1 doesn't work there's unfortunately not much to be done.  You should be able to use the 1.x JAVA-based plugin, though (on the 1.x JAVA IDE, of course).
