### ISSUE TITLE
Having issues accessing files via web site

### ISSUE THREAD

**Issue by godmcse** [earlephilhower/arduino-littlefs-upload#64]
I have spent the last 2 days working on this.  I came across arduino-littlefs-upload and the files seem to upload.  however I can not access them from the web page.  I uploaded a config file,

I test using this code and the file is found:
` File file = LittleFS.open("/config.json", FILE_WRITE);`

however, the webpage cannot find the file.  I uploaded a favicon.gif file and that too is not found.

I tried ./config.json and ./data/config.json I keep getting errors.  what am I doing wrong.  

The plugin does show the files are uploaded successfully.

I am using:
ESP32-WROOM
Arduino IDE 2.3.3
Windows 10
using the plugin to upload the files in /data

Building LittleFS filesystem
Command Line: C:\Users\<user>\AppData\Local\Arduino15\packages\esp32\tools\mklittlefs\3.0.0-gnu12-dc7f933\mklittlefs.exe -c C:\Users\<user>\Documents\Arduino\Stepper_motor\data -p 256 -b 4096 -s 1441792 C:\Users\<user>\AppData\Local\Temp\tmp-5364-kL43OauGt29v-.littlefs.bin
/config.json
/favicon.gif

Uploading LittleFS filesystem
Command Line: C:\Users\<user>\AppData\Local\Arduino15\packages\esp32\tools\esptool_py\4.6\esptool.exe --chip esp32 --port COM13 --baud 115200 --before default_reset --after hard_reset write_flash -z --flash_mode dio --flash_freq 80m --flash_size detect 2686976 C:\Users\<user>\AppData\Local\Temp\tmp-5364-kL43OauGt29v-.littlefs.bin
esptool.py v4.6
Serial port COM13
Connecting....
Chip is ESP32-D0WD-V3 (revision v3.1)
Features: WiFi, BT, Dual Core, 240MHz, VRef calibration in efuse, Coding Scheme None
Crystal is 40MHz
MAC: 88:13:bf:0b:d7:cc
Uploading stub...
Running stub...
Stub running...
Configuring flash size...
Auto-detected Flash size: 4MB
Flash will be erased from 0x00290000 to 0x003effff...
Compressed 1441792 bytes to 2753...
Writing at 0x00290000... (100 %)
Wrote 1441792 bytes (2753 compressed) at 0x00290000 in 10.3 seconds (effective 1118.3 kbit/s)...
Hash of data verified.

Leaving...
Hard resetting via RTS pin...

Completed upload.

web page Console shows this error:
GET http://192.168.10.45/data/config.json net::ERR_ABORTED 500 (Internal Server Error)
or
GET http://192.168.10.45/config.json net::ERR_ABORTED 500 (Internal Server Error)

Any help would be great.

**Comment by earlephilhower** [comment]
Please make a small MCVE that shows the issue, or else it's unlikely that anybody can replicate your problem or help you.  We'll need the partitions.csv and any other scripts or files to build.

In any case, as someone who doesn't use the ESP32, this doesn't look like a filesystem upload issue at all.  IIRC, HTTP status `500` is a *server error*.  You'd just get a `404 Not Found` if the web server was working properly but just didn't have that file.

**Comment by godmcse** [comment]
> Please make a small MCVE that shows the issue, or else it's unlikely that anybody can replicate your problem or help you. We'll need the partitions.csv and any other scripts or files to build.
> 
> In any case, as someone who doesn't use the ESP32, this doesn't look like a filesystem upload issue at all. IIRC, HTTP status `500` is a _server error_. You'd just get a `404 Not Found` if the web server was working properly but just didn't have that file.

i hope this helps
I am trying to control a step motor and i want to access the Config file.  but the file is not accessible.  

```
#include <Arduino.h>
#include <WiFi.h>
#include <AsyncTCP.h>
#include <ESPAsyncWebServer.h>
#include <Stepper.h>
#include <LittleFS.h>
//#include <ArduinoJson.h>


//config file
// const String config_filname ="/config.json";

int Bun0 = 0;
int BunUser = 500;
int Arch0 = 0;
int ArchUser = 500;
int Onerev = 360;
String user_string = "";


// Stepper Motor Settings
const int stepsPerRevolution = 2048;  // change this to fit the number of steps per revolution
#define IN1 19
#define IN2 18
#define IN3 5
#define IN4 17
Stepper myStepper(stepsPerRevolution, IN1, IN3, IN2, IN4);

// Replace with your network credentials
const char* ssid = "Dynimage";
const char* password = "JLJA-2002";

const char* ssidAP = "ESP32-Access-Point";
const char* passwordAP = "1234";


IPAddress staticIP(192, 168, 10, 45);     // ESP32 static IP
IPAddress gateway(192, 168, 10, 1);       // IP Address of your network gateway (router)
IPAddress subnet(255, 255, 255, 0);       // Subnet mask
IPAddress primaryDNS(192, 168, 10, 1);    // Primary DNS (optional)
IPAddress secondaryDNS(192, 168, 10, 3);  // Secondary DNS (optional)

// Create AsyncWebServer object on port 80
AsyncWebServer server(80);

// Search for parameters in HTTP POST request
const char* PARAM_INPUT_1 = "direction";
const char* PARAM_INPUT_2 = "steps";


// Variables to save values from HTML form
String direction;
String steps;

// Variable to detect whether a new request occurred
bool newRequest = false;

// HTML to build the web page
const char index_html[] PROGMEM = R"rawliteral(
<!DOCTYPE html>
<html>
<head>
  <title>Shoe Control test</title>
  <meta name="viewport" content="width=device-width, initial-scale=1">
  <link rel="shortcut icon" type="image/gif" href="./data/favicon.gif"> 
</head>
<body>
  <h1>RT foot Shoe adjustment</h1>
  <h1>Bunion Tightner</h1>
    <form action="/" method="POST">
      <input type="radio" name="direction" value="CW" id="CW" >
      <label for="CW">Tighter</label>
      <input type="radio" name="direction" value="CCW" id="CCW" >
      <label for="CW">Looser</label><br><br><br>
      <label for="steps">Number of steps:</label>
      <input type="number" id="steps" name="steps">
      <input type="submit" id="go" value="GO!">
      <br/>
      <input type="button" name="ubun" id="ubun" value="User Bun" data-id="512"  onClick="recall(204,'r',this.id)">
      <input type="button" name="dbun" id="dbun" value="Default Bun" data-id="1024"  onClick="recall(512,'l',this.id)">
      <br/>
      <input type="button" name="tighter" id="tighter" value="5&deg; Tighter" onClick="SetValu(28,'r',this.id)">
      <input type="button" name="looser" id="looser" value="5&deg; Looser" onClick="SetValu(28,'l',this.id)">
    </form>
 <script type="text/javascript" src="./data/config.json"></script>
<script>
 
  function recall(Steps,Dirct,theid) {
    var ubun = document.getElementById(theid);
	  var Steps = ubun.getAttribute('data-id');
    alert(Steps);
	  document.getElementById('steps').value = Steps;
    if(Dirct == 'l'){
		  document.getElementById('CCW').checked = true;
	  }
	  if(Dirct == 'r'){
		  document.getElementById('CW').checked = true;
	  }

	  document.getElementById('go').click() ;
    //document.forms[0].submit();
	  
  }
  function SetValu(Steps,Dirct,theid) {
    var ubun = document.getElementById('ubun');
	  var dbun = document.getElementById('ubun');

    if(theid == 'tighter'){
      var oldsteps = ubun.getAttribute('data-id');
      var newval = Number(oldsteps) + Steps;
      alert(newval);
      ubun.setAttribute("data-id", newval);
		  alert(ubun.getAttribute('data-id'));
      document.getElementById('steps').value = Steps;
	  }

	  if(theid == 'looser'){
      var oldsteps = ubun.getAttribute('data-id');
      var newval = Number(oldsteps) - Steps;
      ubun.setAttribute("data-id", newval);
		  alert(ubun.getAttribute('data-id'));
      document.getElementById('steps').value = Steps;
	  }
    
    if(Dirct == 'l'){
		  document.getElementById('CCW').checked = true;
	  }
	  
if(Dirct == 'r'){
		  document.getElementById('CW').checked = true;
	  }

	  document.getElementById('go').click() ;
	  
  }
  </script>
</body>
)rawliteral";

// Initialize WiFi
void initWiFi() {
  WiFi.mode(WIFI_STA);
  WiFi.begin(ssid, password);
  Serial.print("Connecting to WiFi ..");
  while (WiFi.status() != WL_CONNECTED) {
    Serial.print('.');
    delay(1000);
  }
  // Configuring static IP
  if (!WiFi.config(staticIP, gateway, subnet, primaryDNS, secondaryDNS)) {
    Serial.println("Failed to configure Static IP");
  } else {
    Serial.println("Static IP configured!");
  }

  Serial.println(WiFi.localIP());
}


void setup() {
  Serial.begin(115200);
  initWiFi();
  /// config file data
  if (!LittleFS.begin(true)) {
    Serial.println("An Error has occurred while mounting SPIFFS");
    return;
  }
  File file = LittleFS.open("/config.json", FILE_WRITE);

  if (!file) {
    Serial.println("{'id':1,'title':'john'}");
    return;
  }
  if (file.print(" We found the file and we are testing it.")) {
    Serial.println("File was found");
    // read all the text written on the file
    /*while (file.available()) {
      Serial.println(file.read());
    }*/
  } else {
    Serial.println("File write failed");
  }
  file.close();
  //end config file

  myStepper.setSpeed(5);

  // Web Server Root URL
  server.on("/", HTTP_GET, [](AsyncWebServerRequest* request) {
    request->send(200, "text/html", index_html);
  });

  // Handle request (form)
  server.on("/", HTTP_POST, [](AsyncWebServerRequest* request) {
    int params = request->params();
    for (int i = 0; i < params; i++) {
      const AsyncWebParameter* p = request->getParam(i);
      if (p->isPost()) {
        // HTTP POST input1 value (direction)
        if (p->name() == PARAM_INPUT_1) {
          direction = p->value().c_str();
          Serial.print("Direction set to: ");
          Serial.println(direction);
        }
        // HTTP POST input2 value (steps)
        if (p->name() == PARAM_INPUT_2) {
          steps = p->value().c_str();
          Serial.print("Number of steps set to: ");
          Serial.println(steps);
        }
      }
    }
    request->send(200, "text/html", index_html);
    newRequest = true;
  });

  server.begin();
}

void loop() {
  // Check if there was a new request and move the stepper accordingly
  if (newRequest) {
    if (direction == "CW") {
      // Spin the stepper clockwise direction
      myStepper.step(steps.toInt());
    } else {
      // Spin the stepper counterclockwise direction
      myStepper.step(-steps.toInt());
    }
    newRequest = false;
  }
}

```

**Comment by earlephilhower** [comment]
Okay, that's actually pretty large and using lots of other libraries that aren't easily used outside of your configl

Can you write a simple ESP32 app that opens up and reads out `config.json` from LittleFS to the Serial port on startup?  That works, then your issue is best opened on the ESP32 Arduino core.  That fails, we can repro here and see what's up.

**Comment by godmcse** [comment]
I even have do a simple codes like this to test yet I can not find the files.   the files list shows the files are on the device, but I can not access them via the URL.  

`
#include <WiFi.h>
#include <AsyncTCP.h>
#include <ESPAsyncWebServer.h>
#include <SPIFFS.h>

const String default_ssid = "WIFI";
const String default_wifipassword = "PASSWORD";
const int default_webserverporthttp = 80;

const char index_html[] PROGMEM = R"rawliteral(
<!DOCTYPE HTML>
<html lang="en">
<head>
  <meta name="viewport" content="width=device-width, initial-scale=1">
  <meta charset="UTF-8">
</head>
<body>
  <p><h1>File Upload</h1></p>
  <p>Free Storage: %FREESPIFFS% | Used Storage: %USEDSPIFFS% | Total Storage: %TOTALSPIFFS%</p>
  <form method="POST" action="/upload" enctype="multipart/form-data"><input type="file" name="data"/><input type="submit" name="upload" value="Upload" title="Upload File"></form>
  <p>After clicking upload it will take some time for the file to firstly upload and then be written to SPIFFS, there is no indicator that the upload began.  Please be patient.</p>
  <p>Once uploaded the page will refresh and the newly uploaded file will appear in the file list.</p>
  <p>If a file does not appear, it will be because the file was too big, or had unusual characters in the file name (like spaces).</p>
  <p>You can see the progress of the upload by watching the serial output.</p>
  <p>%FILELIST%</p>
</body>
</html>
)rawliteral";

String listFiles(bool ishtml = false);

// configuration structure
struct Config {
  String ssid;               // wifi ssid
  String wifipassword;       // wifi password
  int webserverporthttp;     // http port number for web admin
};

// variables
Config config;                        // configuration
AsyncWebServer *server;               // initialise webserver

void setup() {
  Serial.begin(115200);

  Serial.println("Booting ...");

  Serial.println("Mounting SPIFFS ...");
  if (!SPIFFS.begin(true)) {
    // if you have not used SPIFFS before on a ESP32, it will show this error.
    // after a reboot SPIFFS will be configured and will happily work.
    Serial.println("ERROR: Cannot mount SPIFFS, Rebooting");
    rebootESP("ERROR: Cannot mount SPIFFS, Rebooting");
  }

  Serial.print("SPIFFS Free: "); Serial.println(humanReadableSize((SPIFFS.totalBytes() - SPIFFS.usedBytes())));
  Serial.print("SPIFFS Used: "); Serial.println(humanReadableSize(SPIFFS.usedBytes()));
  Serial.print("SPIFFS Total: "); Serial.println(humanReadableSize(SPIFFS.totalBytes()));

  Serial.println(listFiles());

  Serial.println("\nLoading Configuration ...");

  config.ssid = default_ssid;
  config.wifipassword = default_wifipassword;
  config.webserverporthttp = default_webserverporthttp;

  Serial.print("\nConnecting to Wifi: ");
  WiFi.begin(config.ssid.c_str(), config.wifipassword.c_str());
  while (WiFi.status() != WL_CONNECTED) {
    delay(500);
    Serial.print(".");
  }

  Serial.println("\n\nNetwork Configuration:");
  Serial.println("----------------------");
  Serial.print("         SSID: "); Serial.println(WiFi.SSID());
  Serial.print("  Wifi Status: "); Serial.println(WiFi.status());
  Serial.print("Wifi Strength: "); Serial.print(WiFi.RSSI()); Serial.println(" dBm");
  Serial.print("          MAC: "); Serial.println(WiFi.macAddress());
  Serial.print("           IP: "); Serial.println(WiFi.localIP());
  Serial.print("       Subnet: "); Serial.println(WiFi.subnetMask());
  Serial.print("      Gateway: "); Serial.println(WiFi.gatewayIP());
  Serial.print("        DNS 1: "); Serial.println(WiFi.dnsIP(0));
  Serial.print("        DNS 2: "); Serial.println(WiFi.dnsIP(1));
  Serial.print("        DNS 3: "); Serial.println(WiFi.dnsIP(2));

  // configure web server
  Serial.println("\nConfiguring Webserver ...");
  server = new AsyncWebServer(config.webserverporthttp);
  configureWebServer();

  // startup web server
  Serial.println("Starting Webserver ...");
  server->begin();
}

void loop() {
}

void rebootESP(String message) {
  Serial.print("Rebooting ESP32: "); Serial.println(message);
  ESP.restart();
}

// list all of the files, if ishtml=true, return html rather than simple text
String listFiles(bool ishtml) {
  String returnText = "";
  Serial.println("Listing files stored on SPIFFS");
  File root = SPIFFS.open("/");
  File foundfile = root.openNextFile();
  if (ishtml) {
    returnText += "<table><tr><th align='left'>Name</th><th align='left'>Size</th></tr>";
  }
  while (foundfile) {
    if (ishtml) {
      returnText += "<tr align='left'><td>" + String(foundfile.name()) + "</td><td>" + humanReadableSize(foundfile.size()) + "</td></tr>";
    } else {
      returnText += "File: " + String(foundfile.name()) + "\n";
    }
    foundfile = root.openNextFile();
  }
  if (ishtml) {
    returnText += "</table>";
  }
  root.close();
  foundfile.close();
  return returnText;
}

// Make size of files human readable
// source: https://github.com/CelliesProjects/minimalUploadAuthESP32
String humanReadableSize(const size_t bytes) {
  if (bytes < 1024) return String(bytes) + " B";
  else if (bytes < (1024 * 1024)) return String(bytes / 1024.0) + " KB";
  else if (bytes < (1024 * 1024 * 1024)) return String(bytes / 1024.0 / 1024.0) + " MB";
  else return String(bytes / 1024.0 / 1024.0 / 1024.0) + " GB";
}

void configureWebServer() {
  server->on("/", HTTP_GET, [](AsyncWebServerRequest * request) {
    String logmessage = "Client:" + request->client()->remoteIP().toString() + + " " + request->url();
    Serial.println(logmessage);
    request->send_P(200, "text/html", index_html, processor);
  });

  // run handleUpload function when any file is uploaded
  server->on("/upload", HTTP_POST, [](AsyncWebServerRequest *request) {
        request->send(200);
      }, handleUpload);
}

// handles uploads
void handleUpload(AsyncWebServerRequest *request, String filename, size_t index, uint8_t *data, size_t len, bool final) {
  String logmessage = "Client:" + request->client()->remoteIP().toString() + " " + request->url();
  Serial.println(logmessage);

  if (!index) {
    logmessage = "Upload Start: " + String(filename);
    // open the file on first call and store the file handle in the request object
    request->_tempFile = SPIFFS.open("/" + filename, "w");
    Serial.println(logmessage);
  }

  if (len) {
    // stream the incoming chunk to the opened file
    request->_tempFile.write(data, len);
    logmessage = "Writing file: " + String(filename) + " index=" + String(index) + " len=" + String(len);
    Serial.println(logmessage);
  }

  if (final) {
    logmessage = "Upload Complete: " + String(filename) + ",size: " + String(index + len);
    // close the file handle as the upload is now done
    request->_tempFile.close();
    Serial.println(logmessage);
    request->redirect("/");
  }
}

String processor(const String& var) {
  if (var == "FILELIST") {
    return listFiles(true);
  }
  if (var == "FREESPIFFS") {
    return humanReadableSize((SPIFFS.totalBytes() - SPIFFS.usedBytes()));
  }

  if (var == "USEDSPIFFS") {
    return humanReadableSize(SPIFFS.usedBytes());
  }

  if (var == "TOTALSPIFFS") {
    return humanReadableSize(SPIFFS.totalBytes());
  }

  return String();
}`

**Comment by earlephilhower** [comment]
I suggest for this you use the [ESP32 Arduino repo](https://github.com/espressif/arduino-esp32), since you're sure the files are up and running.  There's lots more folks (and the authors) who can help you...

**Comment by godmcse** [comment]
thank you will try it.,

**Comment by godmcse** [comment]
fyi.  i FOUND A SAMPLE THAT WORKS AND WORKING WITH THAT.  THANKS AGAIN FOR THE HELP.
