### ISSUE TITLE
Baud rate problem

### ISSUE THREAD

**Issue by F4HSL-Yves** [earlephilhower/arduino-littlefs-upload#67]
Hello, i have installed the plugin on arduino ide 2.3.3 (windows11). When i use the command “upload little fs” i get an error about the baud rate option :

esptool: error: argument –baud/-b: invalid arg_auto_int value: ‘NaN’
ERROR: Upload failed, error code: 2

here is the command line outputted by your software :
C:\Users\yvesp\AppData\Local\Arduino15\packages\esp32\tools\esptool_py\4.5.1\esptool.exe --chip esp32s3 --port COM10 --baud NaN --before default_reset --after hard_reset write_flash -z --flash_mode dio --flash_freq 80m --flash_size detect 2686976 C:\Users\yvesp\AppData\Local\Temp\tmp-14956-36WGP1eEy8cA-.littlefs.bin

Any idea ?
Best Regards
Yves

PS :  my board is an arduino nano esp32, it seems that the software does not get the right baudrate from arduino context

**Comment by earlephilhower** [comment]
I think your board only does DFU and not esptool/serial.  That's not compatible with the uploader.  There's no workaround other using a more standard board.

**Comment by F4HSL-Yves** [comment]
Ok Tnx, my board is the standard arduino nano esp32, anyway which similar board is compatible with your plugin ?

**Comment by F4HSL-Yves** [comment]
@per1234, tnx a lot, i will try your solution.

**Comment by earlephilhower** [comment]
I've also added a link to that comment in the README.md file.  Thanks, @per1234 !

On a side note, it's not that hard to add add'l upload methods, but I don't have anything that uses DFU upload. I assume that mode can place arbitrary data in arbitrary spots, so if someone has a command line sample for uploading a FS then it'd be possible to add it in (like the OTA and picotool methods just done).  I'd also assume there's a `board.xxxx` variable I can reference to know it's DFU and not normal esptool...
