### ISSUE TITLE
Sparkfun ESP32 Thing Plus Incorrect Partition

### ISSUE THREAD

**Issue by mkinney88** [earlephilhower/arduino-littlefs-upload#68]
I am using the SparkFun Thing Plus - ESP32 WROOM (U.FL) and when I use the LittleFS Uploader it is using the \tools\partitions\default.csv instead of the selected partition from the Arduino IDE selection.

**Comment by earlephilhower** [comment]
Please give a sample project (zipped up since you can't paste INOs or CSVs here), the menu selections you've got, and the output (cut-n-paste text, not image) of the uploader output.
